var anskey_sets = {
	"9grade" : {
		'\\(\\sin 0^\\circ\\)' : '\\(0\\)',
		'\\(\\sin 30^\\circ\\)': '\\(\\frac{1}{2}\\)',
		'\\(\\sin 45^\\circ\\)': '\\(\\frac{\\sqrt{2}}{2}\\)',
		'\\(\\sin 60^\\circ\\)': '\\(\\frac{\\sqrt{3}}{2}\\)',
		'\\(\\sin 90^\\circ\\)' : '\\(1\\)',
		'\\(\\sin 180^\\circ\\)' : '\\(0\\)',
		'\\(\\cos 0^\\circ\\)' : '\\(1\\)',
		'\\(\\cos 30^\\circ\\)': '\\(\\frac{\\sqrt{3}}{2}\\)',
		'\\(\\cos 45^\\circ\\)': '\\(\\frac{\\sqrt{2}}{2}\\)',
		'\\(\\cos 60^\\circ\\)': '\\(\\frac{1}{2}\\)',
		'\\(\\cos 90^\\circ\\)' : '\\(0\\)',
		'\\(\\cos 180^\\circ\\)' : '\\(-1\\)',
		'\\(\\text{tg} 30^\\circ\\)': '\\(\\frac{\\sqrt{3}}{3}\\)',
		'\\(\\text{tg} 45^\\circ\\)': '\\(1\\)',
		'\\(\\text{tg} 60^\\circ\\)': '\\(\\sqrt{3}\\)',
		'\\(\\text{ctg} 30^\\circ\\)': '\\(\\sqrt{3}\\)',
		'\\(\\text{ctg} 45^\\circ\\)': '\\(1\\)',
		'\\(\\text{ctg} 60^\\circ\\)': '\\(\\frac{\\sqrt{3}}{3}\\)',
		},

	"9grade_nomathjax" : {
		'sin0' : '\\(0\\)',
		'sin30': '1/2',
		'sin45': '√2/2',
		'sin60': '√3/2',
		'sin90' : '1',
		'sin180' : '\\(0\\)',
		'cos0' : '1',
		'cos30': '√3/2',
		'cos45': '√2/2',
		'cos60': '1/2',
		'cos90' : '\\(0\\)',
		'cos180' : '-1',
		'tg30': '√3/3',
		'tg45': '1',
		'tg60': '√3',
		'ctg30': '√3',
		'ctg45': '1',
		'ctg60': '√3/3',
		},

	"3gonnametriya" : {
		'\\(\\sin (\\alpha + \\beta )\\)' : '\\(\\sin \\alpha \\cos \\beta +\\cos \\alpha \\sin \\beta\\)',
		'\\(\\sin (\\alpha - \\beta )\\)' : '\\(\\sin \\alpha \\cos \\beta -\\cos \\alpha \\sin \\beta\\)',
		'\\(\\cos (\\alpha + \\beta )\\)' : '\\(\\cos \\alpha \\cos \\beta - \\sin \\alpha \\sin \\beta\\)',
		'\\(\\cos (\\alpha - \\beta )\\)' : '\\(\\cos \\alpha \\cos \\beta + \\sin \\alpha \\sin \\beta\\)',
		'\\(\\text{tg}(\\alpha + \\beta )\\)' : '\\(\\frac{\\text{tg} \\ \\alpha + \\text{tg} \\ \\beta }{1 - \\text{tg} \\ \\alpha \\ \\text{tg} \\ \\beta }\\)',
		'\\(\\text{tg}(\\alpha - \\beta )\\)' : '\\(\\frac{\\text{tg} \\ \\alpha - \\text{tg} \\ \\beta }{1 + \\text{tg} \\ \\alpha \\ \\text{tg} \\ \\beta }\\)',
		'\\(\\sin 2 \\alpha\\)' : '\\(2 \\sin \\alpha \\cos \\alpha \\)',
		'\\(\\cos 2 \\alpha\\)' : '\\(\\cos ^2 \\alpha - \\sin ^2 \\alpha \\)',
		'\\(\\text{tg} \\ 2 \\alpha\\)' : '\\(\\frac{2 \\text{tg} \\ \\alpha }{1 - \\text{tg} ^2 \\ \\alpha }\\)',
		'\\(\\sin ^2 \\frac{\\alpha }{2}\\)' : '\\(\\frac{1 - \\cos \\alpha }{2}\\)',
		'\\(\\cos ^2 \\frac{\\alpha }{2}\\)' : '\\(\\frac{1 + \\cos \\alpha }{2}\\)',
		'\\(\\text{tg} \\ \\frac{\\alpha }{2}\\)' : '\\(\\frac{\\sin \\alpha }{1 + \\cos \\alpha }\\)',
		'\\(\\text{tg} \\ \\frac{\\alpha }{2}\\)' : '\\(\\frac{1 - \\cos \\alpha }{\\sin \\alpha }\\)',
		'\\(\\sin \\alpha \\cos \\beta\\)' : '\\(\\frac{\\sin (\\alpha + \\beta ) + \\sin (\\alpha - \\beta )}{2}\\)',
		'\\(\\sin \\alpha \\sin \\beta\\)' : '\\(\\frac{\\cos (\\alpha - \\beta ) - \\cos (\\alpha + \\beta )}{2}\\)',
		'\\(\\cos \\alpha \\cos \\beta\\)' : '\\(\\frac{\\cos (\\alpha + \\beta ) + \\cos (\\alpha - \\beta )}{2}\\)',
		'\\(\\sin \\alpha + \\sin \\beta\\)' : '\\(2 \\sin \\frac{\\alpha + \\beta }{2} \\cos \\frac {\\alpha - \\beta }{2}\\)',
		'\\(\\sin \\alpha - \\sin \\beta\\)' : '\\(2 \\sin \\frac{\\alpha - \\beta }{2} \\cos \\frac {\\alpha + \\beta }{2}\\)',
		'\\(\\cos \\alpha + \\cos \\beta\\)' : '\\(2 \\cos \\frac{\\alpha + \\beta }{2} \\cos \\frac {\\alpha - \\beta }{2}\\)',
		'\\(\\cos \\alpha - \\cos \\beta\\)' : '\\(-2 \\sin \\frac{\\alpha + \\beta }{2} \\sin \\frac {\\alpha - \\beta }{2}\\)',
		}
}